build:
  main: cmd/apex/main.go
  binary: apex
  ldflags: -s -w -X github.com/shaoye/apex/cmd/apex/version.Version={{.Tag}}
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
  goarch:
    - amd64
    - 386
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^refactor'
